// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAccountant.Database;

#nullable disable

namespace eAccountant.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("eAccountant.Database.Invoice", b =>
                {
                    b.Property<string>("IssuerTaxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverTaxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Pit")
                        .HasColumnType("REAL");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<float?>("Vat")
                        .HasColumnType("REAL");

                    b.HasKey("IssuerTaxId", "ReceiverTaxId", "Number");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("eAccountant.Database.Setting", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
